apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka-broker
          image: bitnami/kafka:3.0.1-debian-11-r36
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_CFG_LISTENERS
              value: EXTERNAL://0.0.0.0:9092,INTERNAL://0.0.0.0:19092
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: EXTERNAL://kafka-service:9092,INTERNAL://localhost:19092
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
            - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
              value: INTERNAL
            - name: KAFKA_BROKER_ID
              value: '1'
            - name: ALLOW_PLAINTEXT_LISTENER
              value: 'yes'
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: zookeeper-service:2181
            - name : KAFKA_ZOOKEEPER_USER
              value: ZOO_USER
            - name: KAFKA_ZOOKEEPER_PASSWORD
              value: ZOO_PASSWORD

