apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service
  labels:
    app: loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: security-demo
  ports:
    - port: 80
      targetPort: SERVER_PORT